name: cd

on:
  push:
    branches: [main]

jobs:
  tests:
    name: Build Prod
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: set up go
        uses: actions/setup-go@v5

      - name: Build app
        run: ./scripts/buildprod.sh
